disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Camp's blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "Discord anim.gif"
secondaryLogo = "frame_00_delay-0.03s.gif"
description = "Camp's blog for hosting and sharing various notes and thoughts about various stuff. It may serve as a document repository for public interest stuff too sometimes. I dunno."

[[params.author.links]]
bluesky = "https://bsky.app/profile/camp.jackle.ca"

[[params.author.links]]
github = "https://github.com/campfred"

[[params.author.links]]
image = "https://furaffinity.net/user/campfred"

[[params.author.links]]
lastfm = "https://www.last.fm/user/campfred"

[[params.author.links]]
music = "https://music.jackle.ca"

[[params.author.links]]
telegram = "https://campfred.t.me"

["params.author"]
name = "Camp"
image = "xmaseve event page 12.profile.png"
headline = "I'm not a miracle worker... Well, not always."
bio = "Big nerd jackal from Canada ğŸ‡¨ğŸ‡¦ who tames ğŸ–¥ï¸s and digital â˜ï¸s by day and (somtimes) ğŸ”Šs, ğŸ’¡s or ğŸ’¿s by night."
