[[main]]
none = "none"

[[main]]
pre = "mug-hot"
name = "Blog"
pageRef = "posts"
identifier = "VezlEO3Lmf"
weight = 1

[[main]]
pre = "castopod"
name = "Mixtapes"
url = "https://music.jackle.ca/@listen/links"
identifier = "YEdyTsJ0Vl"
weight = 2

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "tags"
identifier = "OFZdzCWI7b"
weight = 9_999

[[footer]]
name = "Categories"
pageRef = "categories"
identifier = "BDFpvtAniX"
weight = 9_999
