[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "posts"
identifier = "VezlEO3Lmf"
weight = 1

[[main]]
pre = "music"
name = "Music"
url = "https://music.jackle.ca/@listen/links"
identifier = "YEdyTsJ0Vl"
weight = 2

[[footer]]
none = "none"

[[footer]]
name = "Tags"
pageRef = "tags"
identifier = "OFZdzCWI7b"
weight = 9_999
