[[main]]
pre = "mug-hot"
name = "Blog"
pageRef = "blog"
identifier = "VezlEO3Lmf"
weight = 1

[[main]]
pre = "graduation-cap"
name = "Guides"
pageRef = "guides"
identifier = "zDj8TJLRqG"
weight = 2

[[main]]
pre = "castopod"
name = "Mixtapes"
url = "https://music.jackle.ca/@listen/links"
identifier = "YEdyTsJ0Vl"
weight = 4

[[footer]]
name = "Tags"
pageRef = "tags"
identifier = "OFZdzCWI7b"
weight = 9_999

[[footer]]
name = "Categories"
pageRef = "categories"
identifier = "BDFpvtAniX"
weight = 9_999
